-- 1번
SELECT JOB_NAME
FROM JOB;

-- 2번
SELECT *
FROM DEPARTMENT;

-- 3번
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEE;

-- 4번
SELECT HIRE_DATE, EMP_NAME, SALARY
FROM EMPLOYEE;

-- 5번
SELECT EMP_NAME, SAL_LEVEL
FROM EMPLOYEE
WHERE SALARY >= 2500000;

-- 6번
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE JOB_CODE = 'J3' AND SALARY >= 3500000;

-- 연봉
SELECT EMP_NAME, SALARY * 12
FROM EMPLOYEE;

-- 보너스 금액
SELECT EMP_NAME, SALARY * BONUS "연봉"
FROM EMPLOYEE;

-- 보너스 금액 + 연봉
SELECT EMP_NAME, (SALARY * 12) * (1 + BONUS) AS "연봉(보너스)", '원' AS "단위"
FROM EMPLOYEE
WHERE (SALARY * 12) * (1 + BONUS) IS NOT NULL;

DESC EMPLOYEE;

-- @ 실습 문제 2 --

-- 1번
SELECT EMP_NAME AS "이름", SALARY * 12 AS "연봉", SALARY * BONUS * 12 + SALARY * 12 AS "총 수령액",
(SALARY * BONUS * 12 + SALARY * 12) - (SALARY * 0.03 * 12) AS "실수령액"
FROM EMPLOYEE
WHERE SALARY * BONUS * 12 + SALARY * 12 IS NOT NULL;
-- NVL(SALARY * BONUS * 12 + SALARY * 12, 0) (null) -> 0


-- 2번
SELECT EMP_NAME AS "이름", ROUND (SYSDATE - HIRE_DATE, 0) AS "근무일수", '일' AS " "
FROM EMPLOYEE
ORDER BY SYSDATE - HIRE_DATE DESC;

-- 3번
SELECT EMP_NAME AS "이름", SALARY AS "월급", BONUS AS "보너스율", '%' AS " "
FROM EMPLOYEE
WHERE (SYSDATE - HIRE_DATE) / 365 >= 20 AND BONUS IS NOT NULL
ORDER BY EMP_NAME;


-- DISTINCT
SELECT DISTINCT DEPT_CODE
FROM EMPLOYEE ;

SELECT EMP_NAME, SALARY || '원' AS "월급"
FROM EMPLOYEE;


SELECT EMP_NAME AS "이름",   '폰번호 : ' || PHONE AS "휴대폰"
FROM EMPLOYEE;

SELECT EMP_NAME AS "이름", '급여 : ' || SALARY || '  /  보너스율 : ' || NVL(BONUS* 100, 0) || '%' AS "급여 및 보너스율"
FROM EMPLOYEE;

SELECT EMP_NAME AS "이름", SALARY AS "급여"
FROM EMPLOYEE
WHERE SALARY BETWEEN 3500000 AND 6500000;

SELECT EMP_NAME AS "이름", SALARY || '원' AS "급여"
FROM EMPLOYEE
WHERE SALARY >= 3500000 AND 6500000  >= SALARY;

SELECT *
FROM EMPLOYEE
WHERE HIRE_DATE BETWEEN '90/01/01' AND '01/01/01';

SELECT SALARY AS "급여"
FROM EMPLOYEE
WHERE EMP_NAME = '전지연';

SELECT *
FROM EMPLOYEE
WHERE PHONE NOT LIKE '%3%';

SELECT *
FROM EMPLOYEE
WHERE EMP_NAME NOT LIKE '이%';


-- 실습 문제 3 --

-- 문제 1
SELECT *
FROM EMPLOYEE
WHERE EMP_NAME LIKE '%연';

-- 문제 2
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE PHONE NOT LIKE '010%';

DESC EMPLOYEE;

-- 문제 3
SELECT *
FROM EMPLOYEE
WHERE  (EMAIL LIKE '%s%') AND (DEPT_CODE LIKE 'D9' OR  DEPT_CODE LIKE 'D6') AND (HIRE_DATE BETWEEN '90/01/01' AND '00/12/01') AND (SALARY >= 2700000);

-- 보너스가 없는 사람
SELECT EMP_NAME
FROM EMPLOYEE
WHERE BONUS IS NULL;

SELECT EMP_NAME
FROM EMPLOYEE
WHERE MANAGER_ID IS NULL AND DEPT_CODE IS NULL;

SELECT EMP_NAME
FROM EMPLOYEE
WHERE DEPT_CODE IS NULL AND BONUS IS NOT NULL;

SELECT *
FROM EMPLOYEE
WHERE DEPT_CODE IN('D6', 'D9');


SELECT EMP_NAME AS "이름", SALARY || '원' AS "급여"
FROM EMPLOYEE
WHERE JOB_CODE IN ('J7', 'J2') AND (SALARY > 2000000);

SELECT EMP_ID AS "ID"
FROM EMPLOYEE
ORDER BY EMP_ID DESC;

SELECT *
FROM EMPLOYEE
ORDER BY  1 DESC;
