/* MEMBER TABLE 생성*/
CREATE TABLE MEMBER (
  MEMBER_ID     VARCHAR2(20),
  MEMBER_PWD    VARCHAR2(20),
  MEMBER_NAME   VARCHAR2(20)
);

SELECT *
FROM MEMBER;

DESCRIBE MEMBER;
/* 컬럼 주석 */

COMMENT ON COLUMN MEMBER.MEMBER_ID IS
  '회원아이디';

COMMENT ON COLUMN MEMBER.MEMBER_PWD IS
  '회원비빌번호';

COMMENT ON COLUMN MEMBER.MEMBER_NAME IS
  '회원이름';
  
  /* INSERT */
INSERT INTO MEMBER VALUES ( 'AAA', '1111', 'ㅇㅇㅇ' );

INSERT INTO MEMBER VALUES ( 'AAA', '2222', 'ㅎㅎㅎ' );

TRUNCATE TABLE MEMBER;

DROP TABLE MEMBER;

SELECT *
FROM EMPLOYEE;

DESC EMPLOYEE;

/* CONSTRAINT (EMPLOYEE 테이블 제약조건 확인)*/
SELECT CONSTRAINT_NAME,
       CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMPLOYEE';

/* USER_NOTCONS 테이블 생성 */
  CREATE TABLE USER_NOTCONS
  (
    USER_NO NUMBER,
    USER_ID VARCHAR2(20),
    USER_PWD VARCHAR2(30),
    USER_NAME VARCHAR2(30),
    GENDER VARCHAR2(30),
    PHONE VARCHAR2(30),
    EMAIL VARCHAR2(50)
  );

/* USER_NOTCONS 테이블 제약조건 확인 */
SELECT CONSTRAINT_NAME,
       CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'USER_NOTCONS';

/* USER_NOTCONS  튜플 삽입 */
INSERT INTO USER_NOTCONS 
VALUES(1, NULL, NULL, NULL, NULL, NULL, NULL);

/* USER_NOTCONS 테이블 조회 */
SELECT *
FROM USER_NOTCONS;

/* USER_NOTCONS 테이블 삭제 */
DROP TABLE USER_NOTCONS;

/* USER_NOTCONS 테이블 생성 (NOT NULL 제약조건)*/
  CREATE TABLE USER_NOTCONS
  (
    USER_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    GENDER VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50)  NOT NULL
  );
  
/* 테이블 제약조건 확인 */
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM USER_CONS_COLUMNS
WHERE TABLE_NAME = 'USER_NOTCONS'
UNION
SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'USER_NOTCONS';

/* USER_NOTCONS 테이블 튜플 삽입 */
INSERT INTO USER_NOTCONS
VALUES('1', 'USER1', 'P@SSW0RD', '이름', '남', '010-0000-0000', 'EMAIL@EMAIL.EMAIL');

INSERT INTO USER_NOTCONS
VALUES('2', 'USER2', 'P@SSW0RD', '이름', '남', '010-0000-0000', 'EMAIL@EMAIL.EMAIL');

INSERT INTO USER_NOTCONS
VALUES('3', 'USER3', 'P@SSW0RD', '이름', '남', '010-0000-0000', 'EMAIL@EMAIL.EMAIL');

INSERT INTO USER_NOTCONS
VALUES('4', 'USER4', 'P@SSW0RD', '이름', '남', '010-0000-0000', 'EMAIL@EMAIL.EMAIL');


/* USER_NOTCONS 테이블 생성 (NOT NULL, UNIQUE(USER_ID) 제약조건) */
  CREATE TABLE USER_NOTCONS
  (
    USER_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(20) NOT NULL UNIQUE,
    USER_PWD VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    GENGER VARCHAR2(30) NOT NULL,
    PHONE VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50)  NOT NULL
  ); 
  
/* USER_NOTCONS 테이블 생성 (NOT NULL, UNIQUE(USER_ID), PRIMARY KEY(USER_NO) 제약조건) */
CREATE TABLE USER_NOTCONS
(
      USER_NO NUMBER,
      USER_ID VARCHAR2(20) UNIQUE,
      USER_PWD VARCHAR2(30) NOT NULL,
      USER_NAME VARCHAR2(30) NOT NULL,
      GENDER VARCHAR2(30) NOT NULL,
      PHONE VARCHAR2(30) NOT NULL,
      EMAIL VARCHAR2(50)  NOT NULL,
      PRIMARY KEY(USER_NO)
);

/* USER_NOTCONS 테이블 생성 (NOT NULL, UNIQUE(USER_ID), PRIMARY KEY(USER_NO) 제약조건
튜플 삽입) */
INSERT INTO USER_NOTCONS
VALUES(1, 'USER1', 'P@SSw0RD', '이름', 'F', '10-0000-0000', 'EMAIL@EMAIL.MAIL');

INSERT INTO USER_NOTCONS
VALUES(2, 'USER2', 'P@SSw0RD', '이름', 'M', '10-0000-0000', 'EMAIL@EMAIL.MAIL');


/* CHECK 제약조건 (GENDER = 'M' OR 'F') */
CREATE TABLE USER_NOTCONS
(
      USER_NO NUMBER,
      USER_ID VARCHAR2(20) UNIQUE,
      USER_PWD VARCHAR2(30) NOT NULL,
      USER_NAME VARCHAR2(30) NOT NULL,
      GENDER VARCHAR2(30) CHECK (GENDER IN('F', 'M')),
      PHONE VARCHAR2(30) NOT NULL,
      EMAIL VARCHAR2(50)  NOT NULL,
      PRIMARY KEY(USER_NO)
);


