/* 사원번호 201인 사원 삭제 */
DELETE FROM EMP_TEMP
WHERE EMP_ID LIKE 201;


/* 급여 2백만원인 사원 삭제 (= 두명이 삭제됨)  */
DELETE FROM EMP_TEMP
WHERE SALARY LIKE 2000000;

DROP TABLE MEMBER_TEST01;


/* MEMBER_TEST01 테이블 생성 및 데이터 삽입*/
CREATE TABLE MEMBER_TEST01(
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(20) UNIQUE,
  USER_PWD VARCHAR2(30) NOT NULL,
  USER_NAME VARCHAR2(30)
);

INSERT INTO  MEMBER_TEST01
VALUES(1, 'USER11', '1111', 'ㅇㅇㅇ');

INSERT INTO  MEMBER_TEST01
VALUES(2, 'USER22', '2222', 'ㅁㅁㅁ');

INSERT INTO  MEMBER_TEST01
VALUES(3, 'USER33', '3333', 'ㅅㅅㅅ');


/* MEMBER_TEST01을 참조하는 MEMBER_FOREIGN 테이블 생성 및 데이터 삽입 */
CREATE TABLE MEMBER_FOREIGN(
  USER_ID VARCHAR2(20),
  REGDATE DATE,
  FOREIGN KEY (USER_ID) REFERENCES MEMBER_TEST01(USER_ID)
);

INSERT INTO  MEMBER_FOREIGN
VALUES('USER11', SYSDATE);

INSERT INTO  MEMBER_FOREIGN
VALUES('USER22', SYSDATE);

INSERT INTO  MEMBER_FOREIGN
VALUES('USER33', SYSDATE);

SELECT * FROM MEMBER_FOREIGN;
SELECT * FROM MEMBER_TEST01;

/* 참조하고 있는 테이블에서 삭제 안됨 */
DELETE FROM MEMBER_TEST01
WHERE USER_ID LIKE 'USER11'; -- 참조 하고 있으므로 삭제 불가능

/* 제약조건 비활성 화 (= 삭제 가능하게 됨) */
ALTER TABLE MEMBER_FOREIGN
DISABLE CONSTRAINT SYS_C007204;

DELETE FROM MEMBER_TEST01
WHERE USER_ID LIKE 'USER11'; -- 삭제 가능

/* 데이터 무결성 유지하기 위해 MEMBER_FOREIGN 에서 USER11 삭제 후 제약조건 활성화 */
DELETE FROM MEMBER_FOREIGN
WHERE USER_ID LIKE 'USER11';

ALTER TABLE MEMBER_FOREIGN
ENABLE CONSTRAINT SYS_C007204;

/* TRUNCATE */
TRUNCATE TABLE MEMBER_FOREIGN;

/* 문제 1 */
CREATE TABLE KHACADEMY(
NO NUMBER PRIMARY KEY,
ID VARCHAR2(20) UNIQUE,
PASS VARCHAR2(20) NOT NULL,
NAME VARCHAR2(20) NOT NULL,
NICKNAME VARCHAR2(20) UNIQUE,
GENDER CHAR(1) CHECK (GENDER IN ('F', 'M')),
TEL VARCHAR2(20) DEFAULT '010-0000-0000',
ADDRESS VARCHAR2(90)
);

/* 문제 2 */
INSERT INTO KHACADEMY
VALUES(1, 'hong11', '1234', '홍길동', '동해번쩍', 'M', '010-4958-2333', '경기도');

INSERT INTO KHACADEMY
VALUES(2, 'gogo11', '4444', '고길똥', '둘리세퀴', 'M', DEFAULT , '경상도');

INSERT INTO KHACADEMY
VALUES(3, 'KimDDong', '6658', '김말똥', '내눈은말똥', 'F', '010-6674-8986', '전라도');

INSERT INTO KHACADEMY
VALUES(4, 'sin', '5356', '신구', '니들이게맛을', 'M', '010-8997-1122', '울릉도');

INSERT INTO KHACADEMY
VALUES(5, 'mslove', '5555', '김민수', '영원한ms', 'F', DEFAULT, '서울시');

/* 문제 3*/
UPDATE KHACADEMY
SET PASS = '9999'
WHERE NICKNAME LIKE '내눈은말똥';

/* 문제 4*/
UPDATE KHACADEMY
SET TEL = '없음'
WHERE TEL IN ('010-0000-0000');

/* 문제 5 */
DELETE FROM KHACADEMY
WHERE ID LIKE 'sin';

/* 문제 6 */
TRUNCATE TABLE KHACADEMY;


/* ALTER */
CREATE TABLE MEMBER_TEST(
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(20),
  USER_PWD CHAR(20)
);

/* 테이블에 USER_ID 컬럼 생성 */
ALTER TABLE MEMBER_TEST
ADD USER_NAME VARCHAR2(20);

/* USER_AGE 컬럼 추가 및 DEFAULT 값 설정 */
ALTER TABLE MEMBER_TEST
ADD USER_AGE NUMBER DEFAULT 0;


/* 제약조건이 없으면 중복된 ID가 저장됨 */
INSERT INTO MEMBER_TEST
VALUES (2, 'USER11', '2222', '김말똥', DEFAULT);

/* 제약조건 추가
형식
ALTER TABLE 테이블 명 ADD CONSTRAINT 제약조건(이름) 제약조건(컬럼)*/
ALTER TABLE MEMBER_TEST
ADD CONSTRAINT MEMBER_ID_UNQ UNIQUE(USER_ID); -- 제약조건 이름 (= MEMBER_ID_UNQ)

SELECT COLUMN_NAME, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME LIKE 'MEMBER_TEST';

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME LIKE 'MEMBER_TEST';

/* NOT NULL 제약조건을 추가 할 때에는 ADD가 아닌 MODIFY를 해야함 */
ALTER TABLE MEMBER_TEST
MODIFY USER_PWD CONSTRAINT MEMBER_PWD_NN NOT NULL;

/* 컬럼명 수정 USER_PWD -> PASSWORD */
ALTER TABLE MEMBER_TEST
RENAME COLUMN USER_PWD TO PASSWORD;

/* 컬럼의 데이터 타입 수정
USER_NAME VARCHAR2(20) -> CHAR(30) */
ALTER TABLE MEMBER_TEST
MODIFY USER_NAME CHAR(30);

/* DEFAULT 값 수정 (USER_AGE 값 수정) */
ALTER TABLE MEMBER_TEST
MODIFY USER_AGE DEFAULT 99;

/* USER_AGE 컬럼 삭제 */
ALTER TABLE MEMBER_TEST
DROP COLUMN USER_AGE;

/* 간단 예제
MEMBER_TEST01 테이블의 USER_ID를
MEMBER_FOREIGN 테이블에서 참조 하고 있을 때
MEMBER_TEST01 테이블에서 USER_ID 컬럼을 삭제 하고 싶은 경우*/

ALTER TABLE MEMBER_TEST01
DROP COLUMN USER_ID CASCADE CONSTRAINTS;
-- 해당 컬럼을 삭제할때 제약조건이 연결되어 있다면 해당 제약조건도 모두 삭제하면서 컬럼을 지우는 SQL

/* MEMBER_TEST 테이블 설정된 UNIQUE 제약 조건 삭제 */
ALTER TABLE MEMBER_TEST
DROP CONSTRAINT MEMBER_ID_UNQ;

/* 제약조건 이름 변경
설정되어 있는 제약조건의 이름을 변경 할 수 있음*/
ALTER TABLE MEMBER_TESTs
RENAME CONSTRAINT SYS_C007216 TO MEMBER_NO_PK;

/* 테이블 이름 변경
생성된 테이블의 이름 변경이 가능함 */
ALTER TABLE MEMBER_TEST
RENAME TO MEMBER_TEST_T;

/* 테이블 삭제 */
DROP TABLE MEMBER_TEST_T;

/* 연결된 제약조건도 같이 삭제 */
DROP TABLE MEMBER_TEST_T CASCADE CONSTRAINTS;

/* KHLOVE1에서 사용할 테이블 생성 (GRANT TEST용) */
CREATE TABLE COFFEE(
PRODUCT_NAME VARCHAR2(20) PRIMARY KEY,
PRICE NUMBER NOT NULL,
COMPANY VARCHAR2(20) NOT NULL
);

INSERT INTO COFFEE
VALUES('맥심', 30000, 'MAXIM');

INSERT INTO COFFEE
VALUES('카누', 50000, 'MAXIM');

INSERT INTO COFFEE
VALUES('네스카페', 40000, 'NESCAFE');
