-- 1번
SELECT JOB_NAME
FROM JOB;

-- 2번
SELECT *
FROM DEPARTMENT;

-- 3번
SELECT EMP_NAME, EMAIL, PHONE, HIRE_DATE
FROM EMPLOYEE;

-- 4번
SELECT HIRE_DATE, EMP_NAME, SALARY
FROM EMPLOYEE;

-- 5번
SELECT EMP_NAME, SAL_LEVEL
FROM EMPLOYEE
WHERE SALARY >= 2500000;

-- 6번
SELECT EMP_NAME, PHONE
FROM EMPLOYEE
WHERE JOB_CODE = 'J3' AND SALARY >= 3500000;

-- 연봉
SELECT EMP_NAME, SALARY * 12
FROM EMPLOYEE;

-- 보너스 금액
SELECT EMP_NAME, SALARY * BONUS "연봉"
FROM EMPLOYEE;

-- 보너스 금액 + 연봉
SELECT EMP_NAME, (SALARY * 12) * (1 + BONUS) AS "연봉(보너스)", '원' AS "단위"
FROM EMPLOYEE
WHERE (SALARY * 12) * (1 + BONUS) IS NOT NULL;

DESC EMPLOYEE;

-- @ 실습 문제 2 --

-- 1번
SELECT EMP_NAME AS "이름", SALARY * 12 AS "연봉", SALARY * BONUS * 12 + SALARY * 12 AS "총 수령액",
(SALARY * BONUS * 12 + SALARY * 12) - (SALARY * 0.03 * 12) AS "실수령액"
FROM EMPLOYEE
WHERE SALARY * BONUS * 12 + SALARY * 12 IS NOT NULL;
-- NVL(SALARY * BONUS * 12 + SALARY * 12, 0) (null) -> 0


-- 2번
SELECT EMP_NAME AS "이름", ROUND (SYSDATE - HIRE_DATE, 0) AS "근무일수", '일' AS " "
FROM EMPLOYEE
ORDER BY SYSDATE - HIRE_DATE DESC;

-- 3번
SELECT EMP_NAME AS "이름", SALARY AS "월급", BONUS AS "보너스율", '%' AS " "
FROM EMPLOYEE
WHERE (SYSDATE - HIRE_DATE) / 365 >= 20 AND BONUS IS NOT NULL
ORDER BY EMP_NAME;
