/* 계정생성 */
CREATE USER KHLOVE1 IDENTIFIED BY KHLOVE1;

/* 접속 권한 부여 */
GRANT CONNECT TO KHLOVE1;

/* 테이블 KH.COFFEE  - KHLOVE1에게 SELECT 권한 부여 */
GRANT SELECT ON KH.COFFEE TO  KHLOVE1;

/* 테이블 KH.COFFEE  - KHLOVE1에게 INSERT 권한 부여 */
GRANT INSERT ON KH.COFFEE TO  KHLOVE1;

/* REVOKE 권한 회수 */
REVOKE SELECT, INSERT ON KH.COFFEE FROM KHLOVE1;