CREATE ROLE EMPTYROLE; -- 권한이 없는 ROLE
CREATE ROLE CONNECTROLE; -- 접속권한만 있는 ROLE
CREATE ROLE MANAGERROLE; -- 접속권한 + 테이블 생성 권한 ROLE

GRANT CREATE SESSION TO CONNECTROLE; -- 접속 
GRANT CREATE SESSION,
          CREATE TABLE TO MANAGERROLE; -- 접속 + 테이블 생성
          
REVOKE CREATE TABLE FROM MANAGERROLE; -- MANAGERROLE에서 테이블 생성 권한 회수
          
/*
실습을 위한 사용자 계정 생성
*/
CREATE USER TESTKH IDENTIFIED BY TESTKH;
        
GRANT EMPTYROLE TO TESTKH;
REVOKE EMPTYROLE FROM TESTKH;

GRANT CONNECTROLE TO TESTKH;
REVOKE CONNECTROLE FROM TESTKH;

GRANT MANAGERROLE TO TESTKH;
ALTER USER TESTKH QUOTA UNLIMITED ON SYSTEM; -- SYSTEM SPACE 사용가능하게 함 